# Generated by Django 4.2.4 on 2023-09-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_authors_book_authors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
