# Generated by Django 4.2.4 on 2023-09-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
